language: r
r: devel
cache: packages
warnings_are_errors: false
sudo: true

matrix:
    include:
        - os: linux
          addons:
            apt:
              sources:
                - ubuntu-toolchain-r-test
              packages:
                - g++-5
          env:
             - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

before_install:
    - eval "${MATRIX_EVAL}"

addons:
  apt:
    packages:
      - libudunits2-dev
      - libv8-dev
      - libgsl-dev
      - libgdal-dev
      - libproj-dev


notifications:
  email:
    on_success: change
    on_failure: change
