// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// integrate_ode
Rcpp::DataFrame integrate_ode(std::string& model_name, const std::vector<double>& initial_values, const std::vector<double>& parameters, const std::vector<double>& times);
RcppExport SEXP _pigsustainr_integrate_ode(SEXP model_nameSEXP, SEXP initial_valuesSEXP, SEXP parametersSEXP, SEXP timesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string& >::type model_name(model_nameSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type initial_values(initial_valuesSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type parameters(parametersSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type times(timesSEXP);
    rcpp_result_gen = Rcpp::wrap(integrate_ode(model_name, initial_values, parameters, times));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _pigsustainr_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_pigsustainr_integrate_ode", (DL_FUNC) &_pigsustainr_integrate_ode, 4},
    {"_pigsustainr_rcpp_hello_world", (DL_FUNC) &_pigsustainr_rcpp_hello_world, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_pigsustainr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
