# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

integrate_ode <- function(model_type, times, inits, parameters, dt) {
    .Call(`_pigsustainr_integrate_ode`, model_type, times, inits, parameters, dt)
}

rcpp_hello_world <- function() {
    .Call(`_pigsustainr_rcpp_hello_world`)
}

