# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Integrates a \pkg{pigsustainr} model using C++
#' @param model_type A string for the model type to integrate
#' @param times A vector of integration time steps
#' @param inits A vector of initial values of the state variables
#' @param parameters A vector of parameters
#' @return A dataframe of state variable solutions
integrate_ode <- function(model_name, initial_values, parameters, times) {
    .Call(`_pigsustainr_integrate_ode`, model_name, initial_values, parameters, times)
}

rcpp_hello_world <- function() {
    .Call(`_pigsustainr_rcpp_hello_world`)
}

