# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Integrates a PigSustainR model
#' @param model_type A string for the model type to integrate
#' @param times A vector of integration time steps
#' @param inits A vector of initial values of the state variables
#' @param parameters A vector of parameters
#' @return A dataframe of state variable solutions
integrate_ode <- function(model_type, times, inits, parameters, dt) {
    .Call(`_pigsustainr_integrate_ode`, model_type, times, inits, parameters, dt)
}

